# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

# CRITICAL: This allows this sub-workflow to inherit the IONOS API keys and database secrets
secrets:
  inherit:

env:
  DEPLOYMENT_FOLDER: ./

jobs:
  # Please do not rename this job
  build-project:
    name: build gta
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # 1. SETUP PHP RUNTIME IN GITHUB RUNNER
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Match your target IONOS PHP production version
          extensions: mbstring, xml, ctype, iconv

      # 2. RUN COMPOSER TO GENERATE THE VENDOR FOLDER & PHPDOTENV
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 3fc8f6f0-448a-4d44-a003-198833ddfc2f
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/gta/config.yaml
          action: upload
